import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Barlow, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: "300",
});

const barlow = Barlow({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
